try {
    console.log('Success');
}  catch (error) {
    console.error('Error');
  // core.setFailed(error.message);
}
